### ISSUE TITLE
Dynamic tests are miscounted and unrooted when run in Eclipse

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit-framework#491]
When tests produced by a @TestFactory are run in Eclipse via the JUnitPlatform runner, the dynamic test method is properly shown in the test hierarchy but the tests created by those factories are displayed under the "Unrooted Tests" grouping.  While the dynamic test method is shown as a test container, there are no attached children and the "expander" doesn't work.  The dynamic test methods are however counted as tests.

When the attached JUnit5 tests are run, Eclipse reports 19 tests instead of 16 and the dynamic tests are not shown in the hierarchy under the method that created them.  One other minor issue is that the test method name is being appended to the generated name (without a space or a trailing parenthesis).

![junit5-dynamic-tests-in-eclipse](https://cloud.githubusercontent.com/assets/328333/18208003/95cb1198-70fb-11e6-931f-f549d32cf045.png)

[DynamicTests.java.zip](https://github.com/junit-team/junit5/files/452259/DynamicTests.java.zip)

**Comment by smoyer64** [comment]
Tests appear to be properly counted when run via the JUnit 4 CLI

```
JUnit version 4.12
Sep 02, 2016 12:48:36 PM org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry loadTestEngines
INFO: Discovered TestEngines with IDs: [junit-jupiter]
.....E..............
Time: 0.078
There was 1 failure:
1) Input: 4(testOneThroughTen())
org.opentest4j.AssertionFailedError: 
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:66)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:74)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:123)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:83)
	at DynamicTests.lambda$4(DynamicTests.java:30)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.registerAndExecute(TestFactoryTestDescriptor.java:132)
	at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.lambda$null$0(TestFactoryTestDescriptor.java:92)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.lambda$invokeTestMethod$1(TestFactoryTestDescriptor.java:91)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.invokeTestMethod(TestFactoryTestDescriptor.java:83)
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.execute(MethodTestDescriptor.java:155)
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.execute(MethodTestDescriptor.java:63)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$0(HierarchicalTestExecutor.java:80)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$0(HierarchicalTestExecutor.java:87)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$0(HierarchicalTestExecutor.java:87)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
	at org.junit.platform.runner.JUnitPlatform.run(JUnitPlatform.java:108)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)

FAILURES!!!
Tests run: 16,  Failures: 1
```

For reference, my command line was as follows (this will vary by platform and user):

```
smoyer1@smoyer1-x1-carbon:~/git/psu/junit5-presentation/target/test-classes$ java -cp .:/home/smoyer1/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/smoyer1/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/smoyer1/.m2/repository/org/junit/platform/junit-platform-runner/1.0.0-SNAPSHOT/junit-platform-runner-1.0.0-SNAPSHOT.jar:/home/smoyer1/.m2/repository/org/junit/platform/junit-platform-launcher/1.0.0-SNAPSHOT/junit-platform-launcher-1.0.0-SNAPSHOT.jar:/home/smoyer1/.m2/repository/org/junit/platform/junit-platform-engine/1.0.0-SNAPSHOT/junit-platform-engine-1.0.0-SNAPSHOT.jar:/home/smoyer1/.m2/repository/org/junit/platform/junit-platform-commons/1.0.0-SNAPSHOT/junit-platform-commons-1.0.0-SNAPSHOT.jar:/home/smoyer1/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.0.0-SNAPSHOT/junit-jupiter-engine-5.0.0-SNAPSHOT.jar:/home/smoyer1/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.0.0-SNAPSHOT/junit-jupiter-api-5.0.0-SNAPSHOT.jar:/home/smoyer1/.m2/repository/org/opentest4j/opentest4j/1.0.0-M1/opentest4j-1.0.0-M1.jar org.junit.runner.JUnitCore DynamicTests
```

**Comment by marcphilipp** [comment]
I'm afraid those tests will always show as unrooted when run via the JUnitPlatform runner because JUnit 4 `Descriptions` don't know about their parent.

Regarding the counting and the name displayed in Eclipse I think you should rather open a bug in the Eclipse bug tracker, because both are displayed correctly in the CLI. However, I don't think it's worth the hassle. As long as Eclipse does not support JUnit 5 it will merely be a drop in the bucket.

**Comment by smoyer64** [comment]
Why can't a DynamicTest "remember" it's container?  Isn't the class containing the @TestFactory the DynamicTest's parent regardless of when it's generated?  In any case, I agree that Eclipse shouldn't be counting empty test containers as tests.

As for the CLI example, it only counts raw tests without regards to hierarchy, so I think that's the equivalent of having all the tests unrooted.  Any word on JUnit 5 support in Eclipse?

**Comment by sormuras** [comment]
@smoyer64 JUnit Jupiter + Eclipse _"work in progress"_, according to https://bugs.eclipse.org/bugs/show_bug.cgi?id=488566

**Comment by sbrannen** [comment]
> Why can't a DynamicTest "remember" it's container?

It does know its container.

See the source for `TestFactoryTestDescriptor.registerAndExecute(DynamicTest, int, EngineExecutionListener)`.

And I think you're confusing JUnit 4's `Description

**Comment by smoyer64** [comment]
Yep ... if I had gone back to looking at the JUnit 4 Description I would have seen the problem.  Thanks for indulging me!
